CompanyWebsite/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyWebsite.Controllers
{
    public class AboutUsController : Controller
    {
        // GET: AboutUs
        public ActionResult Index()
        {
            return View();
        }
    }
}

CompanyWebsite/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Net.Mail;
using ViewModel;
using CaptchaMvc.HtmlHelpers;

namespace CompanyWebsite.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(ContactUsViewModel contactUsViewModel)
        {
            if(this.IsCaptchaValid("invalid captcha input"))
            {
                SendEmailToAdmin(contactUsViewModel);
                return View("EmailSent");
            }
            else
            {
                ViewBag.ErrorMessage = "* Invalid captca input.";

                return View("Index");
            }
        }

        private void SendEmailToAdmin(ContactUsViewModel contactUsViewModel)
        {
            var toEmail = ConfigurationManager.AppSettings["ContactUsEmailAddress"];
            var emailSubject = ConfigurationManager.AppSettings["ContactUsEmailSubject"];

            var mailMessage = new MailMessage(contactUsViewModel.Email, toEmail);
            mailMessage.Subject = emailSubject;
            mailMessage.Body = contactUsViewModel.Message;

            var smtpServer = ConfigurationManager.AppSettings["SmtpServer"];
            var smtpPort = int.Parse(ConfigurationManager.AppSettings["SmtpPort"]);

            var smtpClient = new SmtpClient(smtpServer, smtpPort);

            smtpClient.Send(mailMessage);
        }
    }
}

CompanyWebsite/Controllers/DemoAppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyWebsite.Controllers
{
    public class DemoAppsController : Controller
    {
        // GET: DemoApps
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Go()
        {
            return View();
        }
    }
}

CompanyWebsite/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyWebsite.Controllers
{
    public class GamesController : Controller
    {
        // GET: Games
        public ActionResult Index()
        {
            return View();
        }
    }
}

CompanyWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CompanyWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CompanyWebsite/Views/AboutUs/Index.cshtml
@{
    ViewBag.Title = "About Us";
}

<div class="jumbotron" style="min-height:3500px;">
    <h1>ABOUT US</h1>
    <br/>
    <div>
        <div class="textFor50-50Column" style="padding-top:0px;">
            <h2>Origins</h2>
            <p class="lead">

                Hi, I'm Jayd Pather, founder of Rebel Software.
                <br />
                <br />
                I've been a gamer as long as I can remember, and I first tried coding video games when I was 14. I wasn't able to make a complete game as a beginner, but
                I went on to study computer science and work on business applications. At the age of 34, I was ready to release my first game.
            </p>
        </div>
        <div style="float:left; padding-top:20px;">
            <img src="~/Images/founder_headshot.jpg" style="float:left; width:100%; height:auto;" />
            <div style="float:left; clear:left; width:100%; font-size:15px;">
                <div style="float:left;">
                    Jayd Pather
                </div>
                <div style="float:left; padding-left:90px; text-align:right;">
                    Founder
                    <br />
                    Game Designer and Developer
                </div>
            </div>
        </div>
    </div>

    <div style="clear:left;" class="textFor50-50Column">
        <br />
        <h2>Our Game Design</h2>
        <p class="lead">
            We believe there are great aspects to both retro games and modern games. Retro games are simple to learn, but modern games offer realistic 3D graphics. What we're missing is a combination of both.
            <br />
            <br />
            We don't see enough games that combine modern graphics with simple gameplay, and that's the need we aim to fulfill.
        </p>
    </div>

    <div style="clear:left;" class="textFor50-50Column">
        <br />
        <h2>Our Business Model</h2>
        <p class="lead">
            There are two problems with mobile gaming today: in-game ads and in-game currencies.
            <br />
            <br />
            It's too complicated to keep track of in-game currencies like gold, diamonds, and rubies. In our games, you only have to pay for lives, so you know exactly what you're paying for.
            <br />
            <br />
            In-game ads are so annoying, they're more likely to drive players away rather than generate revenue.
            <br />
            <br />
            We're here to bring you the best parts of gaming and cut out all the bullshit: simple gameplay, 3D graphics, zero ads.
        </p>
    </div>
</div>

CompanyWebsite/Views/ContactUs/EmailSent.cshtml
@{
    ViewBag.Title = "EmailSent";
}

<div class="jumbotron">
    <h1>EMAIL SENT</h1>

    <br/>
    <p class="lead">Thanks for your feedback!</p>
</div>

CompanyWebsite/Views/ContactUs/Index.cshtml
@using ViewModel;
@using CaptchaMvc;
@using CaptchaMvc.HtmlHelpers;

@model ContactUsViewModel

@{
    ViewBag.Title = "Contact Us";
}


<div class="jumbotron">
    <h1>CONTACT US</h1>

    <br/>
    
    @using (Html.BeginForm("SendEmail", "ContactUs"))
    {
        <table style="">
            <tbody>
                <tr>
                    <td class="formCell">Name</td>
                    <td class="formCell">
                        @Html.TextBoxFor(x => x.Name)
                    </td>
                </tr>
                <tr>
                    <td class="formCell">Email</td>
                    <td class="formCell">@Html.TextBoxFor(x => x.Email)</td>
                </tr>
                <tr>
                    <td class="formCell">Message</td>
                    <td class="formCell" style="min-width:500px;">@Html.TextAreaFor(x => x.Message, 5, 100, new { style="width:100%; min-width:100%; line-height:1.1;" })</td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td>
                        <br />
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td style="border:solid 1px #C00000; padding:10px;">
                        @Html.Captcha(4)
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td style="color:yellow;">
                        @ViewBag.ErrorMessage
                    </td>
                </tr>
                <tr>
                    <td class="formCell"></td>
                    <td class="formCell">
                        <br/>
                        <input type="submit" value="Send" />
                    </td>
                </tr>
            </tbody>
        </table>
    }
</div>

CompanyWebsite/Views/DemoApps/Go.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_LayoutBusiness.cshtml";
}

<div class="jumbotron" style="margin-top:60px;">
	<h1>Demo Apps</h1>
	<br />

	<h3>My Go demo app</h3>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/UqFVbyvhPR4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

	<h3>My .NET demo app and Android game</h3>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/4YuaIAKMnyg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

	<br />
	<br />

	<h3>Github links:</h3>
	<ul>
		<li>
			<a href="https://github.com/jaydpather/FunctionalCrudForms">Go/.NET scalable business app with RabbitMQ and MongoDB</a>
		</li>
		<li>
			<a href="https://github.com/jaydpather/PVHDemo">Monolith business app with SQL Server</a>
		</li>
		<li>
			<a href="https://github.com/jaydpather/CommonGameLogic">My Android game</a>
		</li>
		<li>
			<a href="https://github.com/jaydpather/UnityGameEngineInterface">Unity interface for my Android game</a>
		</li>
	</ul>
</div>

CompanyWebsite/Views/DemoApps/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_LayoutBusiness.cshtml";
}

<div class="jumbotron" style="margin-top:60px;">
	<h1>Demo Apps</h1>
	<br />
	<h3>An overview of my demo apps</h3>
	<iframe width="560" height="315" src="https://www.youtube.com/embed/4YuaIAKMnyg" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

	<br />
	<br />

	<h3>Github links:</h3> 
	<ul>
		<li>
			<a href="https://github.com/jaydpather/FunctionalCrudForms">Scalable business app with RabbitMQ and MongoDB</a>
		</li>
		<li>
			<a href="https://github.com/jaydpather/PVHDemo">Monolith business app with SQL Server</a>
		</li>
		<li>
			<a href="https://github.com/jaydpather/CommonGameLogic">My Android game</a>
		</li>
		<li>
			<a href="https://github.com/jaydpather/UnityGameEngineInterface">Unity interface for my Android game</a>
		</li>
	</ul>
</div>

CompanyWebsite/Views/Games/Index.cshtml
@{
    ViewBag.Title = "Games";
}

<div class="jumbotron" style="min-height:1600px;">
    <h1>GAMES</h1>
    <br />
	<div>
		<h2>Asteroid Field Navigation</h2>
		<div class="textFor50-50Column">

			<p class="lead">
				Asteroid Field Navigation is our debut game. It's an old school arcade game with modern 3D graphics.
			</p>
			<p class="lead">
				Fly through an asteroid field at high speed and try not to crash!
			</p>
			<p class="lead">
				This game is easy to learn but difficult to master, and has zero ads.
			</p>

			<a target="_blank" href='https://play.google.com/store/apps/details?id=com.ThirdEyeSoftware.AsteroidFieldNavigation&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'>
				<img style="width:100%; height:auto; min-width:200px;" alt='Get it on Google Play' src='https://play.google.com/intl/en_us/badges/images/generic/en_badge_web_generic.png' />
			</a>

			<br />
			<br />
		</div>
		<div style="float:left; border:solid 1px #C00000;">
			<img src="~/Images/AsteroidFieldNavigationScreenshot.png" style="width:100%; height:auto;" />
		</div>
	</div>
</div>

CompanyWebsite/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>REBEL SOFTWARE</h1>
    <br/>
    <p class="lead">Rebel Software is here to make kick-ass games.</p>
    <p class="lead">We're shaking up the world of mobile gaming with our ad-free games.</p>
</div>

<div class="row">
	<div class="col-md-4">
		<h2>@Html.ActionLink("Games", "Index", "Games")</h2>
		<p>
			Check out our games.
		</p>
	</div>
	<div class="col-md-4">
		<h2>@Html.ActionLink("About Us", "Index", "AboutUs")</h2>
		<p>Who are we?</p>
	</div>
	@*
		<div class="col-md-4">
			<h2>@Html.ActionLink("Contact Us", "Index", "ContactUs")</h2>
			<p>Want more info?</p>
		</div>
	*@
</div>

CompanyWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Rebel Software</title
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/customCss")    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="border-bottom:0px solid red;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "RSnavBarItem" })</li>
					<li>@Html.ActionLink("Games", "Index", "Games", null, new { @class = "RSnavBarItem" })</li>
					<li>@Html.ActionLink("About Us", "Index", "AboutUs", null, new { @class = "RSnavBarItem" })</li>
					@*<li>@Html.ActionLink("Contact Us", "Index", "ContactUs", null, new { @class = "RSnavBarItem" })</li>*@
					<li></li>
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div style="float:left; clear:left;">
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Rebel Software</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CompanyWebsite/Views/Shared/_LayoutBusiness.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Rebel Software</title
    @Scripts.Render("~/bundles/modernizr")
	@Styles.Render("~/Content/paintStrapCss")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="border-bottom:0px solid red;">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li></li>
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <div style="float:left; clear:left;">
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Rebel Software</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>